---
sidebar: sidebar 
permalink: create-workspaces.html 
keywords: manage, workspace, snapshot, project 
summary: Ein Arbeitsbereich in NetApp Workload Factory für Builder ist eine Perforce-Darstellung eines Projekts, die auf einem Projekt-Snapshot basiert.  Sie können Arbeitsbereiche als Teil eines Builders-Projekts erstellen. 
---
= Erstellen Sie einen Builders-Arbeitsbereich
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Ein Arbeitsbereich in NetApp Workload Factory für Builder ist eine Perforce-Darstellung eines Projekts zu einem bestimmten Zeitpunkt.  Die Erstellung von Arbeitsbereichen erfolgt auf Grundlage eines Projekt-Snapshots.  Sie können innerhalb eines Builders-Projekts neue Arbeitsbereiche erstellen.  Sie können Arbeitsbereiche über die Perforce-Benutzeroberfläche erstellen.

.Bevor Sie beginnen
Stellen Sie sicher, dass Sie Builders mit dem Perforce Helix Visual Client integriert haben. Weitere Informationen finden Sie unter link:integrate-perforce.html["Integration von Buildern mit Perforce"^] .

.Schritte
. Melden Sie sich bei Perforce an.
. Wählen Sie im Perforce-Menü *Ansicht* > *WF*.
+
Der Anmeldebildschirm von Workload Factory wird in der Perforce-Benutzeroberfläche angezeigt.

. Melden Sie sich bei Workload Factory mit einem der folgendenlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^] .
. Wählen Sie in der Kachel „Builder-Workloads“ die Option *Projekt erstellen* aus.
. Wählen Sie *Arbeitsbereich erstellen*.
. Geben Sie auf der Seite „Workspace-Projekt erstellen“ Folgendes ein:
+
.. Wählen Sie einen Snapshot aus, der als Grundlage für den Arbeitsbereich verwendet werden soll.
.. Geben Sie einen Namen für den Arbeitsbereich ein.
.. Geben Sie optional eine Benutzerkennung ein, um den Arbeitsbereich zu beanspruchen. Diese Kennung sollte mit der Perforce-Benutzer-ID des Entwicklers übereinstimmen, der diesen Arbeitsbereich verwendet.


. Wählen Sie *Erstellen*.


.Ergebnis
Der Arbeitsbereich wird erstellt und in der Liste der Arbeitsbereiche auf der Seite Arbeitsbereiche angezeigt.
