---
sidebar: sidebar 
permalink: learn-builders.html 
keywords: software builders, development, benefits 
summary: NetApp Workload Factory for Builders ist ein Tool zur schnellen Erstellung von Build-Umgebungen für Softwareentwickler. 
---
= Erfahren Sie mehr über NetApp Workload Factory für Bauherren
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Builders ist ein Tool zur schnellen Erstellung von Build-Umgebungen für Softwareentwickler.  Es ermöglicht die schnelle Einrichtung persönlicher Entwicklungsumgebungen, spart Zeit und ermöglicht Entwicklern Self-Service, während DevOps-Teams gleichzeitig die Kontrolle über die Infrastruktur behalten.  Mithilfe von Buildern können Softwareentwickler schnell Arbeitsbereiche erstellen, ohne dass hierfür ein spezieller Datenspeicher oder Kenntnisse der Entwicklungsinfrastruktur erforderlich sind.



== Was ist NetApp Workload Factory für Builder?

NetApp Workload Factory for Builders wurde entwickelt, um die Art und Weise zu optimieren, wie Entwickler verschiedene Versionen ihrer Software verwalten und mit ihnen interagieren. Builders arbeitet mit Perforce Helix Core zusammen, um Softwareversionen sofort zu klonen und Arbeitsbereiche für Entwicklung, Qualitätssicherung und CI/CD zu erstellen.

Mit Builders können Sie ganz einfach ein Projekt erstellen und ein Volume zuweisen, das Ihre Softwareumgebung und ihre Artefakte repräsentiert. Beim Aktualisieren Ihrer Software können Sie Snapshots des Volumes erstellen, um den Zustand Ihrer Software zu diesem Zeitpunkt festzuhalten. Sie können ohne erneute Synchronisierung sofort auf jede Softwareversion zugreifen und so Zeit und Ressourcen sparen.

Durch die Nutzung der Snapshot- und Klonfunktionen von NetApp ONTAP ermöglicht Builders einen schnelleren Zugriff auf verschiedene Versionen Ihrer Software, sodass Sie Updates schneller entwickeln und veröffentlichen können.

Weitere Informationen zu Workload Factory finden Sie imlink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Übersicht über Workload Factory"^] .



== Funktionen der NetApp Workload Factory für Builder

NetApp Workload Factory für Builder bietet die folgenden Funktionen:

* Erstellen, bearbeiten und entfernen Sie Projekte
* Erstellen von Snapshots von definierten Softwareversionen
* Erstellen und Löschen von Workspaces (auf Basis von Klonen)
* Erstellen Sie Zugriffsrichtlinien, um den Zugriff auf ein Projekt zu steuern
* Analyse der Kapazitätsauslastung jedes Projekts
* Kontrolle über die Klongröße und die Aufbewahrung der Klone für jedes Projekt
* Integration in Versionskontrollsysteme wie Perforce




== Projekte und Arbeitsbereiche in Builders

Wenn Sie Builders verwenden, erstellen Sie ein Projekt und weisen ein Volume zu, das Ihre Softwareumgebung und deren Artefakte darstellt. Jedes Mal, wenn Sie eine neue Version der Software erstellen, müssen Sie die Volume-Daten neu synchronisieren und einen Projekt-Snapshot erstellen, um den Volume-Status als bekannte Version zu markieren. Das Projektquellvolumen erhält möglicherweise Rolling Updates und verfügt über mehrere Snapshots, um mehrere Versionen zu markieren. Jeder Snapshot kann sofort als sofortiger Klon verwendet werden, als dediziertes oder gemeinsam genutztes bearbeitbares Repository, das Entwicklern, QA- oder Build-Prozessen zur Verfügung steht. Ein Klon im Kontext einer bestimmten Softwareversion ist ein Arbeitsbereich.



== Automatisierung mit Workload Factory Codebox

Workload Factory führt mit der _Codebox_ eine integrierte Automatisierung ein. Die Codebox bietet folgende Automatisierungsvorteile:

* *Code-Snippet-Generierung*: Infrastructure-as-Code (IAC)-Snippets werden während der Ressourcenerstellung generiert, was eine nahtlose Integration in bestehende Orchestrierungs-Workflows ermöglicht.
* *Infrastructure-as-Code-Copilot*: Die Codebox ist ein Infrastructure-as-Code-Copilot (IaC), der Entwicklern und DevOps dabei hilft, Code zu generieren, um alle von Workload Factory unterstützten Vorgänge auszuführen.
* *Code-Viewer und Automations-Katalog*: Die Codebox bietet einen Code-Viewer für die schnelle Analyse der Automatisierung und einen Automatisierungs-Katalog für eine schnelle spätere Wiederverwendung.




== Kosten

Die Nutzung der Builder-Funktion von Workload Factory ist kostenlos.



== Lizenzierung

Für die Nutzung der Builder-Funktionen von Workload Factory sind keine speziellen Lizenzen von NetApp erforderlich.



== Regionen

Bauherren werden in allen kommerziellen Regionen unterstützt, in denen FSX für ONTAP unterstützt wird. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Unterstützte Amazon Regionen anzeigen."^]

Die folgenden AWS Regionen werden nicht unterstützt:

* China-Regionen
* GovCloud (USA) Regionen
* Geheime Cloud
* Top Secret Cloud




== Hilfe wird abgerufen

Amazon FSx for NetApp ONTAP ist eine AWS-Erstanbieterlösung. Nutzen Sie für Supportanfragen das Support Center in Ihrer AWS Management Console, um ein Ticket zu eröffnen. Wählen Sie „FSx für ONTAP“ und die Kategorie aus und geben Sie dann die erforderlichen Informationen an.

Allgemeine Fragen zu Workload Factory oder Workload Factory-Anwendungen und -Diensten finden Sie unterlink:get-help-builders.html["Hilfe zu Buildern für Workload Factory erhalten"] .
