---
sidebar: sidebar 
permalink: learn-builders.html 
keywords: software builders, development, benefits 
summary: BlueXP  Workload Factory for Builders ist ein Tool zur Erstellung einer schnell erschaffenden Umgebung für Softwarehersteller. 
---
= Erfahren Sie mehr über die BlueXP  Workload-Fabrik für Entwickler
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  Workload Factory for Builders ist ein Tool zur Erstellung einer schnell erschaffenden Umgebung für Softwarehersteller. Es ermöglicht die schnelle Einrichtung persönlicher Entwicklungsumgebungen, spart Zeit und ermöglicht Self-Service für Entwickler, während DevOps-Teams die Kontrolle über die Infrastruktur behalten. Mithilfe von Builders können Softwareentwickler schnell Workspaces erstellen, ohne spezielle Datenspeicher oder ein Verständnis der Entwicklungsinfrastruktur benötigen.



== Was ist eine BlueXP -Workload-Fabrik für Entwickler?

Die BlueXP  Workload Factory for Builders wurde entwickelt, um die Art und Weise zu optimieren, wie Entwickler verschiedene Versionen ihrer Software verwalten und mit ihnen interagieren. Builders können nahtlos in Perforce Helix Core integriert werden, um sofort Klone von Softwareversionen bereitzustellen und sofort einsatzbereite Workspaces für Entwicklungs-, Qualitätssicherungs- und CI/CD-Prozesse zu erstellen.

Mit Builders können Sie ganz einfach ein Projekt erstellen und ein Volume zuweisen, das Ihre Softwareumgebung und deren Artefakte darstellt. Während Sie Ihre Software aktualisieren, können Sie Snapshots des Volumes erstellen, um den Zustand Ihrer Software zu diesem Zeitpunkt zu erfassen. Das bedeutet, dass Sie sofort auf jede Version Ihrer Software zugreifen können, ohne dass Sie sie mit dem Versionskontrollsystem neu synchronisieren müssen, was wertvolle Zeit und Ressourcen spart.

Durch Nutzung der Snapshot- und Klonfunktionen von ONTAP verbessert Builders Ihren Entwicklungs-Workflow, der schnellen Zugriff auf mehrere Versionen Ihrer Software ermöglicht, Entwicklungszyklen beschleunigt und die Markteinführungszeit verkürzt.

Weitere Informationen zur Workload Factory finden Sie im link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Übersicht über die Workload-Fabrik"^].



== Funktionen der BlueXP  Workload Factory for Builders

Die BlueXP  Workload Factory for Builders bietet folgende Funktionen:

* Erstellen, bearbeiten und entfernen Sie Projekte
* Erstellen von Snapshots von definierten Softwareversionen
* Erstellen und Löschen von Workspaces (auf Basis von Klonen)
* Erstellen Sie Zugriffsrichtlinien, um den Zugriff auf ein Projekt zu steuern
* Analyse der Kapazitätsauslastung jedes Projekts
* Kontrolle über die Klongröße und die Aufbewahrung der Klone für jedes Projekt
* Integration in Versionskontrollsysteme wie Perforce




== Projekte und Arbeitsbereiche in Builders

Wenn Sie Builders verwenden, erstellen Sie ein Projekt und weisen ein Volume zu, das Ihre Softwareumgebung und deren Artefakte darstellt. Jedes Mal, wenn Sie eine neue Version der Software erstellen, müssen Sie die Volume-Daten neu synchronisieren und einen Projekt-Snapshot erstellen, um den Volume-Status als bekannte Version zu markieren. Das Projektquellvolumen erhält möglicherweise Rolling Updates und verfügt über mehrere Snapshots, um mehrere Versionen zu markieren. Jeder Snapshot kann sofort als sofortiger Klon verwendet werden, als dediziertes oder gemeinsam genutztes bearbeitbares Repository, das Entwicklern, QA- oder Build-Prozessen zur Verfügung steht. Ein Klon im Kontext einer bestimmten Softwareversion ist ein Arbeitsbereich.



== Betriebsmodi in der Workload Factory

Drei verschiedene Betriebsmodi – _Basis_, _Nur-Lesen_ und _Lesen/Schreiben_ – bieten flexible Optionen für die Bereitstellung innerhalb und außerhalb der Workload Factory. Erhalten Sie im _BASIC_-Modus sofort einen Wert ohne Vertrauen mit Codeschnipseln für die Verwendung außerhalb der Arbeitslast. Erzielen Sie inkrementellen Mehrwert durch inkrementelles Vertrauen in den Modi _Nur-Lesen_ und _Lesen/Schreiben_.

Erfahren Sie mehr über link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["Betriebsmodi in der Workload Factory"^].



== Automatisierung mit Workload Factory Codebox

Workload Factory führt mit der _Codebox_ eine integrierte Automatisierung ein. Die Codebox bietet folgende Automatisierungsvorteile:

* *Code-Snippet-Generierung*: Infrastructure-as-Code (IAC)-Snippets werden während der Ressourcenerstellung generiert, was eine nahtlose Integration in bestehende Orchestrierungs-Workflows ermöglicht.
* *Co-Pilot für Infrastructure-as-Code*: Die Codebox ist ein Co-Pilot für Infrastructure-as-Code (IAC), der Entwicklern und DevOps bei der Erstellung von Code hilft, um jeden von der Workload Factory unterstützten Betrieb auszuführen.
* *Code-Viewer und Automations-Katalog*: Die Codebox bietet einen Code-Viewer für die schnelle Analyse der Automatisierung und einen Automatisierungs-Katalog für eine schnelle spätere Wiederverwendung.




== Kosten

Es gibt keine Kosten für die Nutzung der Builders-Fähigkeit von Workload Factory.



== Lizenzierung

Für die Nutzung der Builders-Funktionen der Workload Factory sind keine speziellen Lizenzen von NetApp erforderlich.



=== Unterstützte Regionen

Bauherren werden in allen kommerziellen Regionen unterstützt, in denen FSX für ONTAP unterstützt wird. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Unterstützte Amazon Regionen anzeigen."^]

Die folgenden AWS Regionen werden nicht unterstützt:

* China-Regionen
* GovCloud (USA) Regionen
* Geheime Cloud
* Top Secret Cloud




== Hilfe wird abgerufen

Amazon FSX für NetApp ONTAP ist eine AWS-First-Party-Lösung. Wenn Sie Fragen oder Probleme des technischen Supports im Zusammenhang mit Ihrem FSX für ONTAP-Filesystem, Ihrer Infrastruktur oder jeder Lösung, die diesen Service verwendet, verwenden Sie das Support-Center in Ihrer AWS-Managementkonsole, um einen Support-Fall für AWS zu eröffnen. Wählen Sie den Service „FSX for ONTAP“ und die entsprechende Kategorie aus. Geben Sie die verbleibenden Informationen an, die zur Erstellung Ihres AWS-Supportfalls erforderlich sind.

Allgemeine Fragen zu den Anwendungen und Dienstleistungen der Arbeitslast-Fabrik oder der Arbeitslast-Fabrik finden Sie unter link:get-help-builders.html["Holen Sie sich Hilfe für Entwickler für Workload Factory"].
