---
sidebar: sidebar 
permalink: learn-builders.html 
keywords: software builders, development, benefits 
summary: NetApp Workload Factory for Builders ist ein Tool zur schnellen Erstellung von Build-Umgebungen für Softwareentwickler. 
---
= Erfahren Sie mehr über NetApp Workload Factory für Bauherren
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Builders ist ein Tool zur schnellen Erstellung von Build-Umgebungen für Softwareentwickler.  Es ermöglicht die schnelle Einrichtung persönlicher Entwicklungsumgebungen, spart Zeit und ermöglicht Entwicklern Self-Service, während DevOps-Teams gleichzeitig die Kontrolle über die Infrastruktur behalten.  Mithilfe von Buildern können Softwareentwickler schnell Arbeitsbereiche erstellen, ohne dass hierfür ein spezieller Datenspeicher oder Kenntnisse der Entwicklungsinfrastruktur erforderlich sind.



== Was ist NetApp Workload Factory für Builder?

NetApp Workload Factory for Builders wurde entwickelt, um die Verwaltung und Interaktion von Entwicklern mit verschiedenen Versionen ihrer Software zu optimieren.  Builders lässt sich nahtlos in Perforce Helix Core integrieren, um sofortige Klone von Softwareversionen bereitzustellen und einsatzbereite Arbeitsbereiche für Entwicklungs-, Qualitätssicherungs- und CI/CD-Prozesse zu erstellen.

Mit Builders können Sie ganz einfach ein Projekt erstellen und ein Volume zuweisen, das Ihre Softwareumgebung und deren Artefakte darstellt. Während Sie Ihre Software aktualisieren, können Sie Snapshots des Volumes erstellen, um den Zustand Ihrer Software zu diesem Zeitpunkt zu erfassen. Das bedeutet, dass Sie sofort auf jede Version Ihrer Software zugreifen können, ohne dass Sie sie mit dem Versionskontrollsystem neu synchronisieren müssen, was wertvolle Zeit und Ressourcen spart.

Durch Nutzung der Snapshot- und Klonfunktionen von ONTAP verbessert Builders Ihren Entwicklungs-Workflow, der schnellen Zugriff auf mehrere Versionen Ihrer Software ermöglicht, Entwicklungszyklen beschleunigt und die Markteinführungszeit verkürzt.

Weitere Informationen zu Workload Factory finden Sie imlink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Übersicht über Workload Factory"^] .



== Funktionen der NetApp Workload Factory für Builder

NetApp Workload Factory für Builder bietet die folgenden Funktionen:

* Erstellen, bearbeiten und entfernen Sie Projekte
* Erstellen von Snapshots von definierten Softwareversionen
* Erstellen und Löschen von Workspaces (auf Basis von Klonen)
* Erstellen Sie Zugriffsrichtlinien, um den Zugriff auf ein Projekt zu steuern
* Analyse der Kapazitätsauslastung jedes Projekts
* Kontrolle über die Klongröße und die Aufbewahrung der Klone für jedes Projekt
* Integration in Versionskontrollsysteme wie Perforce




== Projekte und Arbeitsbereiche in Builders

Wenn Sie Builders verwenden, erstellen Sie ein Projekt und weisen ein Volume zu, das Ihre Softwareumgebung und deren Artefakte darstellt. Jedes Mal, wenn Sie eine neue Version der Software erstellen, müssen Sie die Volume-Daten neu synchronisieren und einen Projekt-Snapshot erstellen, um den Volume-Status als bekannte Version zu markieren. Das Projektquellvolumen erhält möglicherweise Rolling Updates und verfügt über mehrere Snapshots, um mehrere Versionen zu markieren. Jeder Snapshot kann sofort als sofortiger Klon verwendet werden, als dediziertes oder gemeinsam genutztes bearbeitbares Repository, das Entwicklern, QA- oder Build-Prozessen zur Verfügung steht. Ein Klon im Kontext einer bestimmten Softwareversion ist ein Arbeitsbereich.



== Betriebsmodi in Workload Factory

Drei verschiedene Betriebsmodi – _Basic_, _Read-Only_ und _Read/Write_ – bieten flexible Optionen für die Bereitstellung innerhalb und außerhalb von Workload Factory.  Profitieren Sie sofort von Zero-Trust im _Basis_-Modus mit Codeausschnitten zur Verwendung außerhalb von Workload Factory.  Erhalten Sie inkrementelle Werte mit inkrementellem Vertrauen im _Nur-Lese-_ und _Lese-/Schreib-_Modus.

Erfahren Sie mehr über link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["Betriebsmodi in Workload Factory"^] .



== Automatisierung mit Workload Factory Codebox

Workload Factory führt mit der _Codebox_ eine integrierte Automatisierung ein. Die Codebox bietet folgende Automatisierungsvorteile:

* *Code-Snippet-Generierung*: Infrastructure-as-Code (IAC)-Snippets werden während der Ressourcenerstellung generiert, was eine nahtlose Integration in bestehende Orchestrierungs-Workflows ermöglicht.
* *Infrastructure-as-Code-Copilot*: Die Codebox ist ein Infrastructure-as-Code-Copilot (IaC), der Entwicklern und DevOps dabei hilft, Code zu generieren, um alle von Workload Factory unterstützten Vorgänge auszuführen.
* *Code-Viewer und Automations-Katalog*: Die Codebox bietet einen Code-Viewer für die schnelle Analyse der Automatisierung und einen Automatisierungs-Katalog für eine schnelle spätere Wiederverwendung.




== Kosten

Die Nutzung der Builder-Funktion von Workload Factory ist kostenlos.



== Lizenzierung

Für die Nutzung der Builder-Funktionen von Workload Factory sind keine speziellen Lizenzen von NetApp erforderlich.



== Regionen

Bauherren werden in allen kommerziellen Regionen unterstützt, in denen FSX für ONTAP unterstützt wird. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Unterstützte Amazon Regionen anzeigen."^]

Die folgenden AWS Regionen werden nicht unterstützt:

* China-Regionen
* GovCloud (USA) Regionen
* Geheime Cloud
* Top Secret Cloud




== Hilfe wird abgerufen

Amazon FSX für NetApp ONTAP ist eine AWS-First-Party-Lösung. Wenn Sie Fragen oder Probleme des technischen Supports im Zusammenhang mit Ihrem FSX für ONTAP-Filesystem, Ihrer Infrastruktur oder jeder Lösung, die diesen Service verwendet, verwenden Sie das Support-Center in Ihrer AWS-Managementkonsole, um einen Support-Fall für AWS zu eröffnen. Wählen Sie den Service „FSX for ONTAP“ und die entsprechende Kategorie aus. Geben Sie die verbleibenden Informationen an, die zur Erstellung Ihres AWS-Supportfalls erforderlich sind.

Allgemeine Fragen zu Workload Factory oder Workload Factory-Anwendungen und -Diensten finden Sie unterlink:get-help-builders.html["Hilfe zu Buildern für Workload Factory erhalten"] .
