---
sidebar: sidebar 
permalink: requirements-builders.html 
keywords: Builders, FSx, project, projects 
summary: Stellen Sie sicher, dass Workload Factory und AWS ordnungsgemäß eingerichtet sind, bevor Sie mit der Verwendung von NetApp Workload Factory für Builder beginnen.  Dazu gehören Ihre AWS-Anmeldeinformationen, ein bereitgestelltes FSx für ONTAP Dateisystem und mehr. 
---
= Anforderungen an den Ersteller
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Stellen Sie sicher, dass Workload Factory und AWS ordnungsgemäß eingerichtet sind, bevor Sie NetApp Workload Factory for Builders verwenden. Dazu gehören unter anderem Ihre AWS-Anmeldeinformationen und ein bereitgestelltes FSx for ONTAP Dateisystem.

Workload Werksanmeldung und Konto:: Sie müssen https://docs.netapp.com/us-en/workload-setup-admin/sign-up-saas.html["Einrichten eines Kontos bei Workload Factory"^] und melden Sie sich mit einem der https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^] .
AWS Zugangsdaten und Berechtigungen:: Sie müssen Workload Factory AWS-Anmeldeinformationen mit Lese-/Schreibberechtigungen hinzufügen, was bedeutet, dass Sie Workload Factory für Builder im Lese-/Schreibmodus verwenden.


Die Berechtigungen _Basic_ und _read-only_ werden derzeit nicht unterstützt.

https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Erfahren Sie, wie Sie AWS-Anmeldeinformationen zu Workload Factory hinzufügen"^]

FSX für ONTAP-Dateisystem:: Sie benötigen mindestens ein FSX für ONTAP-Dateisystem:
+
--
* Das Dateisystem wird von Builders zum Speichern der von Ihnen erstellten Projekte und Arbeitsbereiche verwendet.
+
Dieses Dateisystem FSX für ONTAP muss FlexVol-Volumen verwenden. FlexGroup Volumes werden nicht unterstützt.

* Sie müssen die AWS-Region, VPC und das Subnetz kennen, in der sich das AWS FSX für ONTAP-Filesystem befindet.
* Sie benötigen mindestens ein Volume im Dateisystem mit der folgenden Konfiguration:
+
** Das Volume muss als NFS-Freigabe konfiguriert sein.
** Das Dateisystem muss mit einem Link konfiguriert sein. https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Weitere Informationen zu Links"^].


* Sie müssen die Tag-Schlüssel-/Wertpaare berücksichtigen, die Sie auf die AWS Ressourcen anwenden möchten, die Teil dieser Implementierung sind (optional).
+
https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Erfahren Sie, wie Sie FSX für ONTAP-Dateisysteme implementieren und managen"^]



--

